title: Stephen's Statements
email: webmaster@stephenduncanjr.com
description: A little bit of everything from Stephen Duncan Jr, a Software Developer in Portland, Oregon
baseurl: ""
url: http://www.stephenduncanjr.com

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Stephen
