title: Stephen's Statements
email: webmaster@stephenduncanjr.com
description: A little bit of everything from Stephen Duncan Jr, a Software Developer in Portland, Oregon
baseurl: ""
url: http://www.stephenduncanjr.com
permalink: /:year/:month/:title:output_ext

exclude:
  - s3_website.yaml

plugins:
  - jekyll-feed
  - jekyll-archives

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Stephen

jekyll-archives:
  enabled:
    - month
    - tags
  permalinks:
    month: '/:year/:month/'
    tag: '/search/label/:name/'
